name: github pages

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - run: mdbook build

      - name: Install static-sitemap-cli
        run: npm install static-sitemap-cli

      - name: Generate sitemap
        run: |
          cd book
          npx sscli --no-clean --base https://jangsc0000.github.io/av1-book-ko

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './book'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2